export const iconList = [
    { className: "k-i-undo" },
    { className: "k-i-redo" },
    { className: "k-i-reset" },
    { className: "k-i-reload k-i-refresh k-i-recurrence" },
    { className: "k-i-non-recurrence" },
    { className: "k-i-reset-sm" },
    { className: "k-i-reload-sm k-i-refresh-sm k-i-recurrence-sm" },
    { className: "k-i-clock" },
    { className: "k-i-calendar" },
    { className: "k-i-save k-i-floppy" },
    { className: "k-i-print k-i-printer" },
    { className: "k-i-edit k-i-pencil" },
    { className: "k-i-delete k-i-trash" },
    { className: "k-i-attachment k-i-clip" },
    { className: "k-i-attachment-45 k-i-clip-45" },
    { className: "k-i-link-horizontal k-i-hyperlink" },
    { className: "k-i-unlink-horizontal k-i-hyperlink-remove" },
    { className: "k-i-link-vertical" },
    { className: "k-i-unlink-vertical" },
    { className: "k-i-lock" },
    { className: "k-i-unlock" },
    { className: "k-i-set-column-position" },
    { className: "k-i-stick" },
    { className: "k-i-unstick" },
    { className: "k-i-cancel" },
    { className: "k-i-cancel-outline" },
    { className: "k-i-cancel-circle" },
    { className: "k-i-check k-i-checkmark" },
    { className: "k-i-check-outline k-i-checkmark-outline k-i-success" },
    { className: "k-i-check-circle k-i-checkmark-circle" },
    { className: "k-i-close k-i-x" },
    { className: "k-i-close-outline k-i-x-outline k-i-error" },
    { className: "k-i-close-circle k-i-x-circle" },
    { className: "k-i-plus" },
    { className: "k-i-plus-outline" },
    { className: "k-i-plus-circle" },
    { className: "k-i-minus k-i-kpi-trend-equal" },
    { className: "k-i-minus-outline" },
    { className: "k-i-minus-circle" },
    { className: "k-i-divide" },
    { className: "k-i-equal" },
    { className: "k-i-not-equal" },
    { className: "k-i-less-or-equal" },
    { className: "k-i-greater-or-equal" },
    { className: "k-i-sort-asc" },
    { className: "k-i-sort-desc" },
    { className: "k-i-unsort" },
    { className: "k-i-sort-clear" },
    { className: "k-i-sort-asc-sm" },
    { className: "k-i-sort-desc-sm" },
    { className: "k-i-filter" },
    { className: "k-i-filter-clear" },
    { className: "k-i-filter-sm" },
    { className: "k-i-filter-sort-asc-sm" },
    { className: "k-i-filter-sort-desc-sm" },
    { className: "k-i-filter-add-expression" },
    { className: "k-i-filter-add-group" },
    { className: "k-i-login" },
    { className: "k-i-logout" },
    { className: "k-i-download" },
    { className: "k-i-upload" },
    { className: "k-i-hyperlink-open" },
    { className: "k-i-hyperlink-open-sm" },
    { className: "k-i-launch" },
    { className: "k-i-window k-i-window-maximize" },
    { className: "k-i-windows k-i-window-restore k-i-tiles" },
    { className: "k-i-window-minimize" },
    { className: "k-i-gear k-i-cog k-i-custom" },
    { className: "k-i-gears k-i-cogs" },
    { className: "k-i-wrench k-i-settings" },
    { className: "k-i-preview k-i-eye" },
    { className: "k-i-zoom k-i-search" },
    { className: "k-i-zoom-in" },
    { className: "k-i-zoom-out" },
    { className: "k-i-pan k-i-move" },
    { className: "k-i-hand" },
    { className: "k-i-cursor" },
    { className: "k-i-calculator" },
    { className: "k-i-cart k-i-shopping-cart" },
    { className: "k-i-connector" },
    { className: "k-i-plus-sm" },
    { className: "k-i-minus-sm" },
    { className: "k-i-kpi-status-deny" },
    { className: "k-i-kpi-status-hold" },
    { className: "k-i-kpi-status-open" },
    { className: "k-i-barcode" },
    { className: "k-i-barcode-outline" },
    { className: "k-i-barcode-scanner" },
    { className: "k-i-qr-code" },
    { className: "k-i-qr-code-outline" },
    { className: "k-i-qr-code-scanner" },
    { className: "k-i-barcode-qr-code-scanner" },
    { className: "k-i-signature" },
    { className: "k-i-accessibility" },
    { className: "k-i-export" },
    { className: "k-i-import" },
  ];
  